### ISSUE TITLE
ImportError: cannot import name 'pickle' from 'rdkit.six.moves' (unknown location)

### ISSUE THREAD

**Issue by garywei944** [Cyril-Grl/AlphaSMILES#1]
Hi Cyril. It seems there are some version conflict between `rdkit` and `pickle`. 

I got the following error msg when running mcts.
```
New tree
Creation of a new data base
Scorer for DFT
Loading scores

Loaded model from disk
Loaded model from disk
Loaded model from disk
Let's begin
 __ 0 0.0
Size of the tree : 1
Height of the tree : 1
Turn 0
Node to expand : __ 0 0.0
New nodes : [_C_ 0 0.0, _O_ 0 0.0, _c_ 0 0.0, _N_ 0 0.0, _n_ 0 0.0, _s_ 0 0.0, _S_ 0 0.0, _[nH]_ 0 0.0, _Cl_ 0 0.0, _o_ 0 0.0, _[NH]_ 0 0.0]
new smiles : [Cc1nc(CC(CNN)N=NNC2n2)cccs1, CCC1CC(=O)N=CCC1COC1, OCc1cccnc1CN1CCCC(=O)NC1, OCC(N)c1ccccc1, c1ccccc1CCCCCCC1CCC(C)(C)=N, c1cno2nccnc2c1O, N1CCN(CCCC2)C(C)CC1, Nc1ccc2c(cn(O)c1)CCN1, n1ccccc1N1CCCC2C(=O)CCCC2, n1cc(C)c2c(Cl)cnn12, s1ncc2o(ccccn2)cc1, s1nc2c(O)c2occ2c(=O)cc1ccc1, SC(c1ncccc1COCC(C)=O)C1, S=CCNCCc1cccc3c1cn1cccc1, [nH]1n(Co22csc2)CCCCC, [nH]1cc(COCC2)cc(C(O)=N2)CCCC, ClC(=O)CCl, Cl=COOCCOCc1cccsc1, on1(C)ccccc2n2c1c1C3C(=O)O), o1cc(CCc2cccc2nc2)C1C, [NH]SC(CC(=O)O)C(N)C1, [NH]c1cn(C)c(N(C)O)C(O)C]
Update
22 smiles to process
22 unique smiles
Traceback (most recent call last):
  File "/home/aris/Projects/AlphaSMILES/main.py", line 24, in <module>
    launch()
  File "/home/aris/Projects/AlphaSMILES/mcts/mcts.py", line 168, in launch
    update(new_smiles)  # (new_node, new_smiles)
  File "/home/aris/Projects/AlphaSMILES/mcts/mcts.py", line 341, in update
    Parallel(n_jobs=p.config['n_jobs'], backend=backend)(delayed(update_smiles)(s) for s in set(new_smiles))
  File "/home/aris/anaconda3/envs/tf2/lib/python3.7/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/home/aris/anaconda3/envs/tf2/lib/python3.7/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/aris/anaconda3/envs/tf2/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/aris/anaconda3/envs/tf2/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/aris/anaconda3/envs/tf2/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/aris/anaconda3/envs/tf2/lib/python3.7/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/home/aris/anaconda3/envs/tf2/lib/python3.7/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/aris/Projects/AlphaSMILES/mcts/mcts.py", line 313, in update_smiles
    smiles.calculation_of_properties()
  File "/home/aris/Projects/AlphaSMILES/mcts/smiles.py", line 188, in calculation_of_properties
    from mcts.properties.properties import Property2D
  File "/home/aris/Projects/AlphaSMILES/mcts/properties/properties.py", line 6, in <module>
    from mcts.properties import sascorer
  File "/home/aris/Projects/AlphaSMILES/mcts/properties/sascorer.py", line 30, in <module>
    from rdkit.six.moves import pickle
ImportError: cannot import name 'pickle' from 'rdkit.six.moves' (unknown location)

Process finished with exit code 1
```

and I fixed this issue by changing line 29-32 of `sascorer.py` to `import pickle`

FYI, here's my dependency versions
```
Package                            Version
---------------------------------- -------------------
absl-py                            0.9.0
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-project                   0.8.3
argh                               0.26.2
asn1crypto                         1.3.0
astroid                            2.3.3
astropy                            4.0.1.post1
astunparse                         1.6.3
atomicwrites                       1.4.0
attrs                              19.3.0
autopep8                           1.5.3
Babel                              2.8.0
backcall                           0.2.0
backports.shutil-get-terminal-size 1.0.0
beautifulsoup4                     4.9.1
bitarray                           1.4.0
bkcharts                           0.2
bleach                             3.1.5
blinker                            1.4
bokeh                              2.1.1
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
cachetools                         4.1.0
cclib                              1.5.post1
certifi                            2020.6.20
cffi                               1.14.0
chardet                            3.0.4
click                              7.1.2
cloudpickle                        1.5.0
clyent                             1.2.2
colorama                           0.4.3
contextlib2                        0.6.0.post1
cryptography                       2.9.2
cycler                             0.10.0
Cython                             0.29.21
cytoolz                            0.10.1
dask                               2.20.0
decorator                          4.4.2
defusedxml                         0.6.0
diff-match-patch                   20200713
distributed                        2.20.0
docutils                           0.16
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
filelock                           3.0.12
flake8                             3.8.3
Flask                              1.1.2
fsspec                             0.7.4
future                             0.18.2
gast                               0.3.3
gevent                             20.6.2
glob2                              0.7
gmpy2                              2.0.8
google-auth                        1.17.2
google-auth-oauthlib               0.4.1
google-pasta                       0.2.0
greenlet                           0.4.16
grpcio                             1.27.2
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.1
hypothesis                         5.20.3
idna                               2.10
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 1.7.0
intervaltree                       3.0.2
ipykernel                          5.3.3
ipython                            7.16.1
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              4.3.21
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.17.1
jeepney                            0.4.3
Jinja2                             2.11.2
joblib                             0.16.0
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.6
jupyter-console                    6.1.0
jupyter-core                       4.6.3
jupyterlab                         2.1.5
jupyterlab-server                  1.2.0
Keras                              2.4.3
Keras-Preprocessing                1.1.0
keyring                            21.2.1
kiwisolver                         1.2.0
lazy-object-proxy                  1.5.0
libarchive-c                       2.9
llvmlite                           0.33.0+1.g022ab0f
locket                             0.2.0
lxml                               4.5.2
Markdown                           3.1.1
MarkupSafe                         1.1.1
matplotlib                         3.2.2
mccabe                             0.6.1
mistune                            0.8.4
mkl-fft                            1.1.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mock                               4.0.2
more-itertools                     8.4.0
mpmath                             1.1.0
msgpack                            1.0.0
multipledispatch                   0.6.0
nbconvert                          5.6.1
nbformat                           5.0.7
networkx                           2.4
nltk                               3.5
nose                               1.3.7
notebook                           6.0.3
numba                              0.50.1
numexpr                            2.7.1
numpy                              1.18.5
numpydoc                           1.1.0
oauthlib                           3.1.0
olefile                            0.46
openpyxl                           3.0.4
opt-einsum                         3.1.0
packaging                          20.4
pandas                             1.0.5
pandocfilters                      1.4.2
parso                              0.7.0
partd                              1.1.0
path                               13.1.0
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             7.2.0
pip                                20.1.1
pkginfo                            1.5.0.1
pluggy                             0.13.1
ply                                3.11
pptree                             3.1
prometheus-client                  0.8.0
prompt-toolkit                     3.0.5
protobuf                           3.12.3
psutil                             5.7.0
ptyprocess                         0.6.0
py                                 1.9.0
pyasn1                             0.4.8
pyasn1-modules                     0.2.7
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycrypto                           2.6.1
pycurl                             7.43.0.5
pydocstyle                         5.0.2
pyflakes                           2.2.0
Pygments                           2.6.1
PyJWT                              1.7.1
pylint                             2.4.4
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
pyrsistent                         0.16.0
PySocks                            1.7.1
pytest                             5.4.3
pytest-arraydiff                   0.3
pytest-astropy                     0.8.0
pytest-astropy-header              0.1.2
pytest-doctestplus                 0.7.0
pytest-openfiles                   0.5.0
pytest-remotedata                  0.3.2
python-dateutil                    2.8.1
python-jsonrpc-server              0.3.4
python-language-server             0.34.1
pytz                               2020.1
PyWavelets                         1.1.1
pyxdg                              0.26
PyYAML                             5.3.1
pyzmq                              19.0.1
QDarkStyle                         2.8.1
QtAwesome                          0.7.2
qtconsole                          4.7.5
QtPy                               1.9.0
regex                              2020.6.8
requests                           2.24.0
requests-oauthlib                  1.3.0
rope                               0.17.0
rsa                                4.0
Rtree                              0.9.4
ruamel-yaml                        0.15.87
scikit-image                       0.16.2
scikit-learn                       0.23.1
scipy                              1.5.0
seaborn                            0.10.1
SecretStorage                      3.1.2
Send2Trash                         1.5.0
setuptools                         49.2.0.post20200714
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.15.0
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.2.2
soupsieve                          2.0.1
Sphinx                             3.1.2
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.3
spyder                             4.1.4
spyder-kernels                     1.9.2
SQLAlchemy                         1.3.18
statsmodels                        0.11.1
sympy                              1.6.1
tables                             3.6.1
tblib                              1.6.0
tensorboard                        2.3.0
tensorboard-plugin-wit             1.6.0
tensorflow                         2.2.0
tensorflow-estimator               2.2.0
termcolor                          1.1.0
terminado                          0.8.3
testpath                           0.4.4
threadpoolctl                      2.1.0
toml                               0.10.1
toolz                              0.10.0
tornado                            6.0.4
tqdm                               4.47.0
traitlets                          4.3.3
typing-extensions                  3.7.4.2
ujson                              1.35
unicodecsv                         0.14.1
urllib3                            1.25.9
watchdog                           0.10.3
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.34.2
widgetsnbextension                 3.5.1
wrapt                              1.12.1
wurlitzer                          2.0.1
xlrd                               1.2.0
XlsxWriter                         1.2.9
xlwt                               1.3.0
yapf                               0.30.0
zict                               2.0.0
zipp                               3.1.0
zope.event                         4.4
zope.interface                     4.7.1
```

**Comment by Cyril-Grelier** [comment]
Hi! If I remember well I had the same kind of problem last year and the lines 29-32 corrected it but it seems that they deleted the module six (https://github.com/rdkit/rdkit/issues/2415). Thank you for the correction! (to be honest I don't remember why I didn't use pickle directly... maybe there was some conflict with rdkit...)
And I just saw that the doc have been deleted from my university server but you can still watch it locally. (Sorry there is "some" spelling mistakes...)
